### T1 [1 балл]. Сделайте калькулятор произвольных выражений, операции следующие: +, -, /, ^, *. скобок нет

In [1]:
def calculate(input_str):
    
    return 0

#### Дополнить еще 2-мя своими тестами

In [20]:
assert calculate("2 + 2 * 2") == 6
assert calculate("345 / 5 * 21") == 1449.
assert calculate("3^3 - 10 + 41 * 3") == 119
assert calculate("42 / 7 * 32") == 192.0

### T2 [1 балл]. Создайте функцию, которая размножает букву, после которой встретилось число, на это число.
HE2LO -> HELLO (число означает сколько раз встречается буква)

In [3]:
def transform_string(inp_string):
    res = ""
    curr_number = 0
    for el in inp_string:
        if el.isdigit():
            curr_number = curr_number * 10 + int(el)
        else:
            if curr_number > 1:
                res += el * curr_number
                curr_number = 0
            else:
                res += el
    return res

#### Дополнить еще 2-мя своими тестами

In [4]:
assert transform_string("HE2LO") == "HELLO"
assert transform_string("HI") == "HI"
assert transform_string("пр12ивет") == "приииииииииииивет"
assert transform_string("2л3у78н65тик") == 'ллуууннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннтттттттттттттттттттттттттттттттттттттттттттттттттттттттттттттттттик'

assert transform_string("BR3UH") == "BRUUUH"
assert transform_string("CRING3E") == "CRINGEEE"

### T3 [1 балл]. Создайте функцию, которая выводит статистик по строке: кол-во гласных, согласных, цифр, строчных букв, прописных букв

In [5]:
def string_stat(inp_string):
    stats = [0, 0, 0, 0, 0]
    l_set = set("у,е,а,о,э,я,и,ю,ы,ё".split(','))
    for letter in inp_string:
        # число?
        if letter.isdigit():
            stats[2] += 1
        else:
            # заглавная?
            if letter.isupper():
                stats[4] += 1
            else:
                # lower case?
                stats[3] += 1
            # гласная? 
            if letter in l_set:
                stats[0] += 1
            else:
                stats[1] += 1
    return tuple(stats)

#### Дополнить еще 2-мя своими тестами

In [6]:
assert string_stat("Тевирп") == (2, 4, 0, 5, 1)
assert string_stat("КоРоВа4") == (3, 3, 1, 3, 3)

assert string_stat("Кринж3") == (1, 4, 1, 4, 1)
assert string_stat("Ба3а") == (2, 1, 1, 2, 1)

### Т4 [1 балл]. Напишите функцию, инвертирующую словарь.
Например, из k - [v_1, v_2] в v_1 - [k_1]

In [7]:
def dict_inverter(input_dict):
    new_dict = {}
    for key, vals in list(input_dict.items()):
        for val in vals:
            if val in new_dict:
                new_dict[val] = [new_dict[val], key]
            else:
                new_dict[val] = key
    return new_dict

#### Дополнить еще 1-м своим тестом

In [8]:
assert dict_inverter({"mango" : ["eatable"], "pillow": ["sleepable"]}) == {"eatable": "mango", "sleepable": "pillow"}
assert dict_inverter({"mango" : ["eatable", "readable"]}) == {"readable":"mango", "eatable":"mango"}
assert dict_inverter({"mango" : ["eatable"], "banana": ["eatable"]}) == {"eatable": ["mango", "banana"]}

assert dict_inverter({"potato" : ["vegetable"], "carrot" : ["vegetable"], "apple": ["fruit"], "melon": ["fruit"]}) == {"vegetable": ["potato", "carrot"], "fruit": ["apple", "melon"]}

### T5 [2 балла]. Средствами NumPy реализуйте функцию для применения метода главных компонент (снижение размерности).
На вход подается двумерная матрица (NxM) и число компонент (k), на выходе получите матрицу сниженной размерности (Nxk)
https://medium.com/analytics-vidhya/understanding-principle-component-analysis-pca-step-by-step-e7a4bb4031d9
#### Протестируйте ее на некоторой матрице

In [9]:
import numpy as np

def custom_pca(X, n_components):
    # Нормализация X
    X_normed = X.copy().T
    X_normed = (X - X.mean(0)) / X.std(0)
    
    # берем матрицу ковариации
    X_cov = np.cov(X_normed, rowvar = False)
    
    # пользуемся симметричностью матрицы
    v, u = np.linalg.eigh(X_cov)
    
    return X_normed @ (u[:, np.argsort(v)[:-n_components-1:-1]])

C:\Users\Elf\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Elf\anaconda3\lib\site-packages\numpy\.libs\libopenblas.4SP5SUA7CBGXUEOC35YP2ASOICYYEQZZ.gfortran-win_amd64.dll
C:\Users\Elf\anaconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [10]:
from sklearn.decomposition import PCA

sample = np.random.randn(10, 3)

sample_normed = sample.copy().T
sample_normed = (sample - sample.mean(0)) / sample.std(0)

pca = PCA(n_components=2)
pca.fit(sample_normed)
true_pca = pca.transform(sample_normed)

print(f"Было:\n{sample}\nСтало:\n{custom_pca(sample, n_components = 2)}\nsklearn:\n{true_pca}")

Было:
[[ 0.12855898  0.79267729 -1.47228315]
 [ 0.55238917  0.1218536  -0.73261414]
 [-0.44594187  1.47047105 -0.20317209]
 [-0.42241354 -0.06238897 -1.59190042]
 [-0.95433959  0.61291177 -1.33059138]
 [-0.44079691 -1.77185725 -0.57686061]
 [ 0.37121249  0.54660981  0.05380531]
 [ 0.35990676  0.64924272  0.47736774]
 [-1.9013492   1.02534338  0.58768878]
 [ 0.49825192 -0.49103517  0.82386727]]
Стало:
[[ 0.01511869  0.99784202]
 [-0.89665841  0.15496251]
 [ 1.19214036 -0.38711815]
 [-0.17127301  1.49290135]
 [ 0.90488703  1.23649001]
 [-1.5009424   0.6985698 ]
 [-0.32957822 -0.76272875]
 [-0.20990434 -1.26004313]
 [ 2.25535702 -0.70525854]
 [-1.25914672 -1.46561712]]
sklearn:
[[ 0.01511869  0.99784202]
 [-0.89665841  0.15496251]
 [ 1.19214036 -0.38711815]
 [-0.17127301  1.49290135]
 [ 0.90488703  1.23649001]
 [-1.5009424   0.6985698 ]
 [-0.32957822 -0.76272875]
 [-0.20990434 -1.26004313]
 [ 2.25535702 -0.70525854]
 [-1.25914672 -1.46561712]]


### Т6 [4 балла]. Напишите в виде класса NashNumPy свой NumPy, но выполняющий матричные операции только на одномерных и двумерных массивах. Должны быть реализованы следующие операции (в случае, если по правилам линейной алгебры такая операция невозможна, то должна возвращаться соответствующая ошибка):
- создание объекта класса NashNumPy - через список, через заполнение 0, через заполнение 1
- красивое распечатывание объекта класса
- применение некоторой (подаваемой на вход) функции ко всем элементам массива
- размерность объекта класса
- матричное сложение (и разность)
- матричное произведение
- произведение Адамара
- вертикальное соединение
- горизонтальное соединение

#### Напишите собственные проверки работоспособности функции

In [11]:
# необходимо для копирования
from copy import deepcopy

class NashNumPy:
    
    def __init__(self, arr):
        """
        Инициализация списком
        """
        self.data = arr
        self.size = (len(arr), len(arr[0]))
    
    def zeros(self, size):
        """
        Инициализация нулями заданного размера
        """
        self.data = [[0 for _ in range(size[1])] for _ in range(size[0])] 
        
    def ones(self, size):
        """
        Инициализация единицами заданного размера
        """
        self.data = [[1 for _ in range(size[1])] for _ in range(size[0])] 
    
    def __str__(self):
        """
        Преобразование в string для функции print
        """
        str_print = '['
        for i, row in enumerate(self.data):
            if i == self.size[0] - 1:
                str_print += '[ ' + ' '.join(str(e) for e in row) + ' ]]'
            else:
                str_print += '[ ' + ' '.join(str(e) for e in row) + ' ]' + '\n'
        return str_print
        
    def __repr__(self):
        """
        Перегрузка вывода без print
        """
        return str(self)
        
    def __add__(self, other):
        """
        Сумма объектов одинаковой длины
        """
        assert self.size == other.size
        result = []
        for i in range(self.size[0]):
            row = []
            for j in range(self.size[1]):
                row.append(self.data[i][j] + other.data[i][j])
            result.append(row)
        return NashNumPy(result)
    
    def __sub__(self, other):
        """
        Разность объектов одинаковой длины
        """
        assert self.size == other.size
        result = []
        for i in range(self.size[0]):
            row = []
            for j in range(self.size[1]):
                row.append(self.data[i][j] - other.data[i][j])
            result.append(row)
        return NashNumPy(result)
    
    def __mul__(self, other):
        """
        Умножение на число
        """
        result = []
        for i in range(self.size[0]):
            row = []
            for j in range(self.size[1]):
                row.append(self.data[i][j] * other)
            result.append(row)
        return NashNumPy(result)
    
    
    def mm(self, mtx):
        """
        Матричное умножение
        """
        assert self.size[1] == mtx.size[0] or (mtx.size[0] == 1 and self.size[1] == mtx.size[1])
        result = []
        
        if mtx.size[0] == 1:
            # случай вектора
            for i, row in enumerate(self.data):
                buf = 0
                for j in range(mtx.size[1]):
                    buf += row[j] * mtx.data[0][j]
                result.append(buf)
        else:
            for i, row in enumerate(self.data):
                new_row = []
                # идем по колоннам второго операнда
                for j in range(mtx.size[1]):
                    buf = 0
                    for k in range(self.size[1]):
                        buf += row[k] * mtx.data[k][j]
                    new_row.append(buf)
                result.append(new_row)
        
        return NashNumPy(result)
    
    def hadamard(self, mtx):
        """
        Произведение Адамара
        """
        assert self.size == mtx.size
        result = []
        for i in range(self.size[0]):
            row = []
            for j in range(self.size[1]):
                row.append(self.data[i][j] * mtx.data[i][j])
            result.append(row)
        return NashNumPy(result)
    
    def hstack(self, vec):
        """
        Горизонтальное присоединение
        """
        assert self.size[0] == vec.size[0]
        # копируем массив
        result = deepcopy(self.data)
        for i in range(self.size[0]):
            for j in range(vec.size[1]):
                result[i].append(vec.data[i][j])
        return NashNumPy(result)
    
    def vstack(self, vec):
        """
        Вертикальное присоединение
        """
        assert self.size[1] == vec.size[1]
        # копируем массив
        result = deepcopy(self.data)
        for i in range(vec.size[0]):
            result.append(vec.data[i])
        return NashNumPy(result)

In [12]:
a_orig = [[1,2],[3,4]]
b_orig = [[5, 6]]
c_orig = [[7.5], [8.2]]
d_orig = [[11,32],[32,4]]
e_orig = [[1,0],[0,1]]


a = NashNumPy(a_orig)
b = NashNumPy(b_orig)
c = NashNumPy(c_orig)
d = NashNumPy(d_orig)
e = NashNumPy(e_orig)

a_np = np.array(a_orig)
b_np = np.array(b_orig)
c_np = np.array(c_orig)
d_np = np.array(d_orig)
e_np = np.array(e_orig)


print(e, a, b, c, d, sep='\n---\n')

[[ 1 0 ]
[ 0 1 ]]
---
[[ 1 2 ]
[ 3 4 ]]
---
[[ 5 6 ]]
---
[[ 7.5 ]
[ 8.2 ]]
---
[[ 11 32 ]
[ 32 4 ]]


In [13]:
assert (a + a).data == (a * 2).data
a + a, a * 2

([[ 2 4 ]
 [ 6 8 ]],
 [[ 2 4 ]
 [ 6 8 ]])

In [14]:
assert (a + d).data == (a_np + d_np).tolist()
(a + d).data, (a_np + d_np).tolist()

([[12, 34], [35, 8]], [[12, 34], [35, 8]])

In [15]:
assert a.mm(d).data == (a_np @ d_np).tolist()
assert a.mm(e).data == (a_np @ e_np).tolist()
assert a.mm(c).data == (a_np @ c_np).tolist()
assert b.mm(c).data == (b_np @ c_np).tolist()

print(a.mm(d), a.mm(e), a.mm(c), b.mm(c), sep='\n --- \n')

[[ 75 40 ]
[ 161 112 ]]
 --- 
[[ 1 2 ]
[ 3 4 ]]
 --- 
[[ 23.9 ]
[ 55.3 ]]
 --- 
[[ 86.69999999999999 ]]


In [16]:
assert a.hadamard(e).data == np.multiply(a_np, e_np).tolist()

print(a.hadamard(e))

[[ 1 0 ]
[ 0 4 ]]


In [17]:
assert c.hstack(c).data == np.hstack((c_np, c_np)).tolist()

print(c, c.hstack(c), sep='\n --- \n')

[[ 7.5 ]
[ 8.2 ]]
 --- 
[[ 7.5 7.5 ]
[ 8.2 8.2 ]]


In [18]:
assert a.hstack(d).data == np.hstack((a_np, d_np)).tolist()

print(a, d, a.hstack(d), sep='\n --- \n')

[[ 1 2 ]
[ 3 4 ]]
 --- 
[[ 11 32 ]
[ 32 4 ]]
 --- 
[[ 1 2 11 32 ]
[ 3 4 32 4 ]]


In [19]:
assert b.vstack(a).data == np.vstack((b_np, a_np)).tolist()

print(b, a, b.vstack(a), sep='\n --- \n')

[[ 5 6 ]]
 --- 
[[ 1 2 ]
[ 3 4 ]]
 --- 
[[ 5 6 ]
[ 1 2 ]
[ 3 4 ]]
